spring:
  application:
    name: uaa-provider
server:
  port: 7701
  servlet:
    context-path: /uaa-provider
eureka:
  instance:
    instance-id: 127.0.0.1:7001
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
