server:
  port: 7001  #该 Module 的端口号
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称，
  server:
    enable-self-preservation: true #开启自我保护
    eviction-interval-timer-in-ms: 60000 #扫描失效服务的间隔时间（单位毫秒，默认是60*1000毫秒，即60秒）
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版服务注册中心